// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzlxxtfrepkqrbbvqoon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6bHh4dGZyZXBrcXJiYnZxb29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDY2MDksImV4cCI6MjA2OTkyMjYwOX0.pGDbmr-6P58zrkgsvj_3XOmc4PgoBytw7FdPturCeNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});